apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: amdocs-manager-hpa1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: amdocsfailuremonitor
  minReplicas: 4
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70