apiVersion: apps/v1
kind: Deployment
metadata:
  name: amdocsfailuremonitor
spec:
  selector:
    matchLabels:
      app: amdocsfailuremonitor
  template:
    metadata:
      labels:
        app: amdocsfailuremonitor
    spec: 
      containers:        
        - image: californibrs/amdocsfailuremonitor
          name: amdocsfailuremonitor
          env:
          - name: PYTHONUNBUFFERED
            value: "1"          
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"